//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRollManagementSyatem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PayRollManagementSystemEntities : DbContext
    {
        public PayRollManagementSystemEntities()
            : base("name=PayRollManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_departments> tbl_departments { get; set; }
        public virtual DbSet<tbl_employee> tbl_employee { get; set; }
        public virtual DbSet<tbl_employeeworkingstatus> tbl_employeeworkingstatus { get; set; }
        public virtual DbSet<VW_GETEMPLOYEE> VW_GETEMPLOYEE { get; set; }
        public virtual DbSet<tbl_Attendance> tbl_Attendance { get; set; }
    }
}
