//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRollManagementSyatem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Attendance
    {
        public int a_id { get; set; }
        public Nullable<int> a_emp_id_fk { get; set; }
        public Nullable<int> a_day { get; set; }
        public Nullable<int> a_month { get; set; }
        public Nullable<int> a_year { get; set; }
        public string a_timein { get; set; }
        public string a_timeout { get; set; }
        public Nullable<int> a_difference { get; set; }
    
        public virtual tbl_employeeworkingstatus tbl_employeeworkingstatus { get; set; }
        public virtual tbl_employee tbl_employee { get; set; }
    }
}
