//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRollManagementSyatem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_employee()
        {
            this.tbl_employeeworkingstatus = new HashSet<tbl_employeeworkingstatus>();
            this.tbl_Attendance = new HashSet<tbl_Attendance>();
        }
    
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_contact { get; set; }
        public string emp_cnic { get; set; }
        public Nullable<System.DateTime> emp_dob { get; set; }
        public string emp_img { get; set; }
        public Nullable<bool> emp_Gender { get; set; }
        public string emp_email { get; set; }
        public Nullable<System.DateTime> emp_hiredate { get; set; }
        public Nullable<bool> emp_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_employeeworkingstatus> tbl_employeeworkingstatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Attendance> tbl_Attendance { get; set; }
    }
}
