//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRollManagementSyatem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_departments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_departments()
        {
            this.tbl_employeeworkingstatus = new HashSet<tbl_employeeworkingstatus>();
        }
    
        public int dep_id { get; set; }
        public string dep_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_employeeworkingstatus> tbl_employeeworkingstatus { get; set; }
    }
}
