//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRollManagementSyatem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employeeworkingstatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_employeeworkingstatus()
        {
            this.tbl_Attendance = new HashSet<tbl_Attendance>();
        }
    
        public int status_id { get; set; }
        public Nullable<int> status_emp_fk { get; set; }
        public Nullable<int> status_dep_fk { get; set; }
        public Nullable<int> status_year { get; set; }
        public Nullable<double> status_basicsalary { get; set; }
        public Nullable<double> status_bouns { get; set; }
        public Nullable<double> status_medical { get; set; }
        public Nullable<int> status_casualleaves { get; set; }
        public Nullable<int> status_sickleaves { get; set; }
        public Nullable<int> status_halfdays { get; set; }
        public Nullable<int> status_annualleaves { get; set; }
    
        public virtual tbl_departments tbl_departments { get; set; }
        public virtual tbl_employee tbl_employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Attendance> tbl_Attendance { get; set; }
    }
}
